const JobCache = require('../models/JobCache');

const scholarships = [
  {
    external_id: 'scholarship_fulbright',
    title: 'Fulbright Foreign Student Program',
    company: 'U.S. Department of State',
    description: 'The Fulbright Program offers grants to graduate students, young professionals and artists to study, teach or conduct research in the United States. Fully funded scholarships covering tuition, living expenses, and airfare.',
    tags: ['Graduate', 'Research', 'Fully Funded', 'USA', 'Masters', 'PhD'],
    location: 'United States',
    salary: 'Fully Funded',
    apply_url: 'https://foreign.fulbrightonline.org/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_gates_cambridge',
    title: 'Gates Cambridge Scholarship',
    company: 'Gates Cambridge Trust',
    description: 'The Gates Cambridge Scholarship programme was established in 2000 by a donation from the Bill and Melinda Gates Foundation. It offers full-cost scholarships to outstanding applicants from countries outside the UK to pursue a full-time postgraduate degree at University of Cambridge.',
    tags: ['Graduate', 'Cambridge', 'Fully Funded', 'UK', 'Masters', 'PhD'],
    location: 'Cambridge, UK',
    salary: 'Fully Funded',
    apply_url: 'https://www.gatescambridge.org/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_rhodes',
    title: 'Rhodes Scholarship',
    company: 'Rhodes Trust',
    description: 'The Rhodes Scholarship is the oldest and most prestigious international fellowship program in the world. Rhodes Scholars are chosen from 64 countries to study at the University of Oxford.',
    tags: ['Graduate', 'Oxford', 'Fully Funded', 'UK', 'Leadership'],
    location: 'Oxford, UK',
    salary: 'Fully Funded',
    apply_url: 'https://www.rhodeshouse.ox.ac.uk/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_daad',
    title: 'DAAD Scholarships for International Students',
    company: 'DAAD (German Academic Exchange Service)',
    description: 'DAAD offers scholarships for international students and researchers to study and conduct research in Germany. Includes masters, doctoral and postdoctoral programs.',
    tags: ['Graduate', 'Germany', 'Masters', 'PhD', 'Research', 'Funded'],
    location: 'Germany',
    salary: '€934/month stipend',
    apply_url: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_chevening',
    title: 'Chevening Scholarship',
    company: 'UK Government',
    description: "Chevening is the UK government's international scholarships programme that offers full funding to study a one-year master's degree at any UK university. It is funded by the Foreign, Commonwealth & Development Office.",
    tags: ['Graduate', 'UK', 'Masters', 'Fully Funded', 'Government'],
    location: 'United Kingdom',
    salary: 'Fully Funded',
    apply_url: 'https://www.chevening.org/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_erasmus',
    title: 'Erasmus Mundus Joint Masters Scholarships',
    company: 'European Commission',
    description: 'Erasmus Mundus Joint Master Degrees are integrated international study programmes delivered by a consortium of higher education institutions. Scholarships cover tuition fees, a living allowance, and travel costs.',
    tags: ['Graduate', 'Europe', 'Masters', 'Fully Funded', 'International'],
    location: 'Europe',
    salary: 'Fully Funded',
    apply_url: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_commonwealth',
    title: 'Commonwealth Scholarships',
    company: 'Commonwealth Scholarship Commission',
    description: 'Commonwealth Scholarships are funded by the UK government and offered to citizens of Commonwealth countries for postgraduate study and professional development in the UK.',
    tags: ['Graduate', 'UK', 'Commonwealth', 'Masters', 'PhD', 'Funded'],
    location: 'United Kingdom',
    salary: 'Fully Funded',
    apply_url: 'https://cscuk.fcdo.gov.uk/scholarships/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_adb',
    title: 'ADB-Japan Scholarship Program',
    company: 'Asian Development Bank',
    description: 'The ADB-Japan Scholarship Program provides an opportunity for well-qualified citizens of ADB\'s developing member countries to pursue postgraduate studies at designated academic institutions in the Asia-Pacific region.',
    tags: ['Graduate', 'Asia', 'Masters', 'Funded', 'Development'],
    location: 'Asia-Pacific',
    salary: 'Fully Funded',
    apply_url: 'https://www.adb.org/work-with-us/careers/jsp-scholarship',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_aga_khan',
    title: 'Aga Khan Foundation International Scholarship',
    company: 'Aga Khan Foundation',
    description: 'The Aga Khan Foundation provides a limited number of scholarships each year for postgraduate studies to outstanding students from developing countries who have no other means of financing their studies.',
    tags: ['Graduate', 'Masters', 'PhD', 'Developing Countries', 'Funded'],
    location: 'Multiple Countries',
    salary: 'Partial/Full Funding',
    apply_url: 'https://www.akdn.org/akf-scholarships',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_sn_bose',
    title: 'S.N. Bose Scholars Program',
    company: 'IUSSTF & WINStep Forward',
    description: 'The S.N. Bose Scholars Program is a prestigious fellowship for Indian undergraduate and graduate students to conduct research at US universities and institutions during summer.',
    tags: ['Research', 'USA', 'Undergraduate', 'Graduate', 'STEM', 'Summer'],
    location: 'United States',
    salary: '$1200/month stipend + airfare',
    apply_url: 'https://www.iusstf.org/program/sn-bose-scholars-program',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_inspire',
    title: 'INSPIRE Scholarship (DST)',
    company: 'Department of Science & Technology, India',
    description: 'INSPIRE (Innovation in Science Pursuit for Inspired Research) is a program of DST for attracting talent to study of science at an early age and establishing a critical human resource pool for strengthening and expanding the science and technology system.',
    tags: ['Undergraduate', 'India', 'STEM', 'Science', 'Government'],
    location: 'India',
    salary: '₹80,000/year',
    apply_url: 'https://online-inspire.gov.in/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_pm_research',
    title: 'Prime Minister Research Fellowship (PMRF)',
    company: 'Ministry of Education, India',
    description: 'PMRF is a prestigious research fellowship scheme that aims to attract the best talent into research, especially from IITs, IISc, and NIT. Fellows receive a monthly fellowship of Rs. 70,000-80,000.',
    tags: ['PhD', 'Research', 'India', 'IIT', 'NIT', 'Government', 'STEM'],
    location: 'India',
    salary: '₹70,000-80,000/month',
    apply_url: 'https://www.pmrf.in/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_kishore',
    title: 'Kishore Vaigyanik Protsahan Yojana (KVPY)',
    company: 'Indian Institute of Science',
    description: 'KVPY (now replaced by INSPIRE SHE) is a national program in Basic Sciences, initiated and funded by the Department of Science and Technology, Government of India, to attract highly motivated students for pursuing basic science courses and research career in science.',
    tags: ['Undergraduate', 'India', 'Science', 'STEM', 'Prestigious'],
    location: 'India',
    salary: '₹5,000-7,000/month',
    apply_url: 'https://kvpy.iisc.ac.in/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_google_lime',
    title: 'Google Lime Scholarship',
    company: 'Google',
    description: 'Google Lime Scholarship is for students with disabilities who are pursuing degrees in Computer Science or related fields.',
    tags: ['Undergraduate', 'Graduate', 'Computer Science', 'Google', 'Technology'],
    location: 'USA / Canada',
    salary: '$10,000',
    apply_url: 'https://buildyourfuture.withgoogle.com/scholarships',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_microsoft_ada',
    title: 'Microsoft Ada Lovelace Scholarship',
    company: 'Microsoft',
    description: 'Microsoft offers the Ada Lovelace Fellowship to support women in technology pursuing their graduate degrees at universities across the world.',
    tags: ['Graduate', 'Women in Tech', 'Microsoft', 'Computer Science', 'Technology'],
    location: 'Worldwide',
    salary: 'Tuition + living stipend',
    apply_url: 'https://www.microsoft.com/en-us/research/academic-program/ada-lovelace-fellowship/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_harvard_financial_aid',
    title: 'Harvard University Financial Aid',
    company: 'Harvard University',
    description: 'Harvard\'s financial aid program is one of the most generous in the world. Over 70% of Harvard graduates leave debt-free. Students from families earning less than $75,000 typically receive full scholarships.',
    tags: ['Undergraduate', 'USA', 'Harvard', 'Need-Based', 'Fully Funded'],
    location: 'Cambridge, MA, USA',
    salary: 'Up to fully funded',
    apply_url: 'https://college.harvard.edu/financial-aid',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_mit_aid',
    title: 'MIT Scholarship & Financial Aid',
    company: 'MIT',
    description: 'MIT meets 100% of demonstrated financial need for all admitted students through scholarships, grants, and work-study. MIT never includes student loans in financial aid packages.',
    tags: ['Undergraduate', 'USA', 'MIT', 'STEM', 'Need-Based', 'Fully Funded'],
    location: 'Cambridge, MA, USA',
    salary: 'Up to fully funded',
    apply_url: 'https://financialaid.mit.edu/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_tata_trust',
    title: 'Tata Trusts Scholarship',
    company: 'Tata Trusts',
    description: 'Tata Trusts offers scholarships to meritorious students from underprivileged backgrounds for undergraduate and postgraduate studies in India and abroad.',
    tags: ['Undergraduate', 'Graduate', 'India', 'Need-Based', 'Merit'],
    location: 'India and Abroad',
    salary: 'Up to ₹10 Lakhs/year',
    apply_url: 'https://www.tatatrusts.org/scholarships',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_jn_tata',
    title: 'JN Tata Endowment Loan Scholarship',
    company: 'JN Tata Endowment',
    description: 'JN Tata Endowment Loan Scholarship is awarded to Indian students for higher studies abroad. The loan scholarship is later converted to a grant upon return to India and making contributions to the country.',
    tags: ['Graduate', 'India', 'Abroad', 'Prestigious', 'Loan Scholarship'],
    location: 'Worldwide',
    salary: 'Up to ₹10 Lakhs',
    apply_url: 'https://jntataendowment.org/',
    posted_at: new Date(),
  },
  {
    external_id: 'scholarship_national_merit',
    title: 'National Merit Scholarship',
    company: 'National Merit Scholarship Corporation',
    description: 'National Merit Scholarship Program is an academic competition for recognition and scholarships that began in 1955. High school students who meet published program entry and participation requirements are eligible.',
    tags: ['Undergraduate', 'USA', 'Merit', 'Academic Excellence'],
    location: 'United States',
    salary: '$2,500 - Full Tuition',
    apply_url: 'https://www.nationalmerit.org/',
    posted_at: new Date(),
  },
];

async function seedScholarships() {
  try {
    const ops = scholarships.map(s => ({
      updateOne: {
        filter: { external_id: s.external_id },
        update: {
          $set: {
            ...s,
            source: 'scholarship',
            type: 'scholarship',
            is_remote: false,
            job_type: 'scholarship',
            // Never expires
            expires_at: new Date('2099-12-31'),
          },
        },
        upsert: true,
      },
    }));

    const JobCache = require('../models/JobCache');
    await JobCache.bulkWrite(ops);
    console.log(`🎓 Seeded ${scholarships.length} scholarships`);
  } catch (err) {
    console.error('Scholarship seed error:', err.message);
  }
}

module.exports = seedScholarships;
